spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true
      port: 9080
  jpa:
    show-sql: true
    properties.hibernate.format_sql: true
  sql:
    init:
      encoding: UTF-8
      mode: embedded
      schema-locations: classpath*:/schema/*

sftp:
  server-address: server_address
  private-key-id: private_key_id
